### ISSUE TITLE
Create new groups throws exception

### ISSUE THREAD

**Issue by jenniferpiz** [CodepathGroup8-JenniferSonali/LetMeetHappen#26]
Pulled latest changes b04f449e134e1e6a30ffe4b675134597b9301195.  Clicking on the  new group 
 icon in toolbar produces exception below.

10-29 10:28:06.356 26815-26815/com.example.skarwa.letmeethappen E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.example.skarwa.letmeethappen, PID: 26815
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.skarwa.letmeethappen/com.example.skarwa.letmeethappen.activities.NewGroupCreateActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
                                                                                      at android.app.ActivityThread

**Comment by skarwa10** [comment]
fixed...used singleTop Launch mode.
