### ISSUE TITLE
limit date options to just 2 dates in new event fragment 

### ISSUE THREAD

**Issue by skarwa10** [CodepathGroup8-JenniferSonali/LetMeetHappen#6]
at present we can provide unlimited number of dates from the calender. Better to restrict it to just 2 .

**Comment by jenniferpiz** [comment]
Currently it only gets 2 from all selected dates. So it is already kinda limited.

**Comment by skarwa10** [comment]
we might need to make the edit text not clickable...once date are selected...i think that was the way i was able to save 6 dates...let me reproduce this again.
